### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by R3VANEK** [xmavv/marsColonization#1]
- `get_coins`, `get_resources` są niewłaściwymi nazwami kolumn bazy. Takie nazewnictwo jest raczej używane w przypadku funkcji, niż kolumn w tabeli, bo sugeruje jakąś logikę "getowania" informacji. Sugerujemy zmianę nazwy na 'coins' i 'resources'
- Sugerujemy zmianę nazwy kolumny `Tasks.task_time` na `Tasks.duration` żeby nie powtarzać w nazwie kolumny nazwy tabeli
- Nazwa tabeli 'Done_tasks' sugeruje, że nie jest to zwykła tabela pośrednia wiele-do-wielu, tylko zawiera również kolumny odpowiedzialne za logikę sprawdzenia statusu zadania. Jeśli tego nie brakuje, to sugerujemy zmienienie nazwy na 'tasks_users'
- Czy będziecie limitowali jakie typy mogą przyjmować taski i budynki? Bo jeśli tak, to może warto byłoby dorobić oddzielne tabele 'tasks_types' i 'buildings_types' które służyłyby jako enumy poprawnych wartości w połączeniu z relacją jeden-do-wielu
- Nazwa 'workers_number' jest niekonsekwentna, w innych miejscach takich jak 'Workers.biologists' które też jest polem typu Int, nie jest użyta końcówka 'number'

**Comment by xmavv** [comment]
dzieki za feedback. 😎

pozmienialismy nazwy, jest o wiele lepiej, mysle ze tego nam brakowalo.

co do enumów, naprawde swietny pomysl, dziekujemy za niego, jednak nie stworzylismy nowych tabel, a dodalismy po prostu enum jako pole w tabeli, ktore moze przyjmowac okreslone nazwy.

w tabeli done_task beda przechowywane wykonane zadania dla pojedynczego uzytkownika, zmienimy nazwe tabeli na users_tasks aby bardziej odpowiadala temu co tam się znajduje.
