### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by fpekal** [xmavv/marsColonization#8]
- Plik `data_base_diagram.pdf` jakoś jest rozjechany (tabela Buildings zasłania tabelę Users i połączenie między tabelą Users_Tasks, a Tasks przechodzi pod tabelą
- Z powodu, że jest to dosyć złożona aplikacja, to mieliśmy trudności z poprawnym uruchomieniem jej komponentów. Proponujemy użycie Dockera.
- Metody `GET /api/v1/users` i `GET /api/v1/users/:username` pozwalaja na odczytanie haseł wszystkich użytkowników.
- Interfejs naprawdę ładnie wygląda (a przynajmniej ekran logowania, do którego udało nam się dostać xd, reszty nie widzieliśmy)
 
![image](https://github.com/user-attachments/assets/0795b38b-72fa-4ec3-a02e-3f9e8d31ad30)

**Comment by xmavv** [comment]
poprawilismy diagram, na google docsach byl dobry, tutaj sie rozjechal...

implementacja calego api jest jeszcze w formie testow , wiec na pewno zajmiemy się sprawa hasel, dziekujemy za przypomnienie

co do zlozonosci aplikacji, mamy swiadomosc , ze jest dosc duza.
poprawilismy readme aby lepiej mozna bylo poruszac sie po folderach, oraz dodalismy informacje jak wlaczyc frontend i backend, tak aby lepiej mozna bylo testowac aplikacje!
